name: 🛎️ Component Request
description: File an issue to request adding a new component to the library
title: "[Request] <title>"
labels: "component request"
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for submitting this issue!
        
        _Don't forget to add a title above!_
        
        Please follow guidelines and only submit one issue or pull request per single component.
        
        ---
  - type: checkboxes
    id: check_duplicates
    attributes:
      label: Is there an existing issue or pull request for this?
      description: Please search to see if an issue or pull request already exists for this component request.
      options:
        - label: I have searched the existing issues and pull requests
          required: true
  - type: input
    id: component
    attributes:
      label: New component being requested
      description: Use the format 'manufactuer manufactuer_part_number'.
      placeholder: DJ DJCOMP123-4
    validations:
      required: true
  - type: dropdown
    id: library_types
    attributes:
      label: Impacted library types
      description: Select all types of library files impacted.
      multiple: true
      options:
        - Symbol
        - Footprint
        - Model (3D)
  - type: textarea
    id: issue_body
    attributes:
      label: Issue body
      description: Please add any relevant information, such as links to manufacturer documentation.
      placeholder: |
        Requesting new component: DJCOMP123-4.
        Datasheet found at https://www.google.com.
        ...
    validations:
      required: true
  - type: dropdown
    id: review
    attributes:
      label: Has this component completed a review for viability?
      description: Components should be reviewed for compliance, cost, and logistics before commitment.
      multiple: false
      options:
        - No, review not complete
        - Yes, review is complete
    validations:
      required: true
