name: 🛠️ Component Error
description: File an issue to report component errors requiring repairs
title: "[Error] <title>"
labels: "component error"
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for submitting this issue!
        
        _Don't forget to add a title above!_
        
        Please follow guidelines and only submit one issue or pull request per single component.
        
        ---
  - type: checkboxes
    id: check_duplicates
    attributes:
      label: Is there an existing issue or pull request for this?
      description: Please search to see if an issue or pull request already exists for this component error.
      options:
        - label: I have searched the existing issues and pull requests
          required: true
  - type: input
    id: component
    attributes:
      label: Component requiring repair
      description: Use the format 'manufactuer manufactuer_part_number'.
      placeholder: DJ DJCOMP123-4
    validations:
      required: true
  - type: dropdown
    id: library_types
    attributes:
      label: Impacted library types
      description: Select all types of library files impacted.
      multiple: true
      options:
        - Symbol
        - Footprint
        - Model (3D)
    validations:
      required: true
  - type: textarea
    id: issue_body
    attributes:
      label: Issue body
      description: Please add any relevant information, such as links to manufacturer documentation.
      placeholder: |
        Pins 5 and 6 on footprint DJ DJCOMP123-4 are incorrectly swapped.
        Datasheet found at https://www.google.com.
        ...
    validations:
      required: true
  - type: dropdown
    id: nightly
    attributes:
      label: Has this component been flagged by any other open issues or pull requests?
      description: This may improve response time by allowing multiple issues to be closed at once.
      multiple: false
      options:
        - Unsure, I need to check
        - Yes, referenced issues and/or pull requests are noted in the issue body
        - No, there are no other references currently open
      default: 2
    validations:
      required: true
